# Generated by Django 6.0.2 on 2026-03-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IMAPGSEMagneticField",
            fields=[
                (
                    "time",
                    models.DateTimeField(
                        db_column="time_utc",
                        help_text="Time for the data.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "bx_gse",
                    models.FloatField(
                        db_column="B_GSE_x",
                        help_text="GSE 'x' component of the magnetic field.",
                    ),
                ),
                (
                    "by_gse",
                    models.FloatField(
                        db_column="B_GSE_y",
                        help_text="GSE 'y' component of the magnetic field.",
                    ),
                ),
                (
                    "bz_gse",
                    models.FloatField(
                        db_column="B_GSE_z",
                        help_text="GSE 'z' component of the magnetic field.",
                    ),
                ),
                (
                    "b_mag",
                    models.FloatField(
                        db_column="B_magnitude",
                        help_text="Modulus of the magnetic field.",
                    ),
                ),
            ],
            options={
                "db_table": "ialirt_mag",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SOGSEMagneticField",
            fields=[
                (
                    "time",
                    models.DateTimeField(
                        db_column="time",
                        help_text="Time for the data.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "bx_gse",
                    models.FloatField(
                        db_column="B_x",
                        help_text="GSE 'x' component of the magnetic field.",
                    ),
                ),
                (
                    "by_gse",
                    models.FloatField(
                        db_column="B_y",
                        help_text="GSE 'y' component of the magnetic field.",
                    ),
                ),
                (
                    "bz_gse",
                    models.FloatField(
                        db_column="B_z",
                        help_text="GSE 'z' component of the magnetic field.",
                    ),
                ),
                (
                    "b_mag",
                    models.FloatField(
                        db_column="B_mod", help_text="Modulus of the magnetic field."
                    ),
                ),
            ],
            options={
                "db_table": "solo_L2_mag-gse-ll-internal",
                "managed": False,
            },
        ),
    ]
