# Generated by Django 6.0.2 on 2026-03-18 10:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imapgsemagneticfield",
            options={},
        ),
        migrations.AlterModelOptions(
            name="sogsemagneticfield",
            options={},
        ),
    ]
