# Generated by Django 6.0.2 on 2026-03-19 09:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_imapgsemagneticfield_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imapgsemagneticfield",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="sogsemagneticfield",
            options={"managed": False},
        ),
    ]
