# Configuration file for the timeseries plots

spacecrafts = ["IMAP", "SO"] # List of all spacecrafts to include
default_spacecraft = "IMAP"  # The spacecraft to display as default

[[plots]]
title = "Magnetic field"
unit = "nT"

[plots.measurements.bx_gse]
label = "Bx GSE"
traces = {IMAP = "red", SO = "blue"}

[plots.measurements.by_gse]
label = "By GSE"
traces = {IMAP = "indianred", SO = "dodgerblue"}

[plots.measurements.bz_gse]
label = "Bz GSE"
traces = {IMAP = "lightsalmon", SO = "powderblue"}

[[plots]]
title = "Phi GSE"
unit = "deg"

[plots.measurements.lon_gse]
label = "Phi GSE"
traces = {IMAP = "red", SO = "blue"}

[[plots]]
title = "Density"
unit = "1/cm³"

[plots.measurements.density]
label = "Density"
traces = {IMAP = "red", SO = "blue"}

[[plots]]
title = "Speed"
unit = "km/s"

[plots.measurements.speed]
label = "Speed"
traces = {IMAP = "red", SO = "blue"}

[[plots]]
title = "Temperature"
unit = "k"

[plots.measurements.temperature]
label = "Temperature"
traces = {IMAP = "red", SO = "blue"}
