# Configuration file for the timeseries plots

spacecrafts = [
    "IMAP",
    "SO",
    "SOLAR-1",
    "ACE",
] # List of all spacecrafts to plot traces for
default_spacecraft = "IMAP" # The spacecraft to display as default

[[plots]]
title = "Magnetic field"
unit = "nT"

[plots.measurements.b_mag]
label = "|B|"
traces = {IMAP = "red", SO = "blue", "SOLAR-1" = "black", "ACE" = "brown"}

[plots.measurements.bx_gsm]
label = "Bx GSM"
spacecraft_labels = {SO = "Bx GSE"}
traces = {IMAP = "red", SO = "blue", "SOLAR-1" = "black", "ACE" = "brown"}

[plots.measurements.by_gsm]
label = "By GSM"
spacecraft_labels = {SO = "By GSE"}
traces = {IMAP = "indianred", SO = "dodgerblue", "SOLAR-1" = "darkslategray", "ACE" = "sienna"}

[plots.measurements.bz_gsm]
label = "Bz GSM"
traces = {IMAP = "lightsalmon", SO = "powderblue", "SOLAR-1" = "lightslategray", "ACE" = "maroon"}

[[plots]]
title = "Phi GSM"
unit = "deg"

[plots.measurements.phi_gsm]
label = "Phi GSM"
spacecraft_labels = {SO = "Phi GSE"}
traces = {IMAP = "red", SO = "blue", "SOLAR-1" = "black", "ACE" = "brown"}

[[plots]]
title = "Theta GSM"
unit = "deg"

[plots.measurements.theta_gsm]
label = "Theta GSM"
spacecraft_labels = {SO = "Theta GSE"}
traces = {IMAP = "red", SO = "blue", "SOLAR-1" = "black", "ACE" = "brown"}

[[plots]]
title = "Density"
unit = "1/cm³"

[plots.measurements.density]
label = "Density"
traces = {IMAP = "red", SO = "blue", "SOLAR-1" = "black", "ACE" = "brown"}

[[plots]]
title = "Speed"
unit = "km/s"

[plots.measurements.speed]
label = "Speed"
traces = {IMAP = "red", SO = "blue", "SOLAR-1" = "black", "ACE" = "brown"}

[[plots]]
title = "Temperature"
unit = "k"

[plots.measurements.temperature]
label = "Temperature"
traces = {IMAP = "red", SO = "blue", "SOLAR-1" = "black", "ACE" = "brown"}
