name: Test and build

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        python-version: ['3.13']

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          prune-cache: false
          activate-environment: true
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync

      - name: Run mypy
        run: mypy .

      - name: Install so-pipeline tools
        run: uv tool install --python 3.10 "git+https://${{ secrets.GH_TOKEN }}@github.com/ImperialCollegeLondon/so-pipeline-core-rse@dalonsoa-patch-1"

      - name: Run tests
        run: pytest

      - name: Install doc dependencies
        run: uv sync --group doc

      - name: Check that documentation builds cleanly with MkDocs
        if: matrix.os == 'ubuntu-latest'
        run: mkdocs build --strict
